### ISSUE TITLE
Zoom and Drag Problem

### ISSUE THREAD

**Issue by lcoombe** [rterp/GMapsFX#69] opened 2016-07-12 20:07 UTC
Hello,
We used some code from a previous blog of yours (https://rterp.wordpress.com/2014/04/25/gmapsfx-add-google-maps-to-your-javafx-application/), but when we try to zoom by double-clicking the map, we then cannot drag the map.
Here is a picture showing what happens when we try to drag and move the map after zooming with a double click:
![gmapsfx-error](https://cloud.githubusercontent.com/assets/11697335/16781722/5f412b6e-4831-11e6-98e3-e2d5ebd82da8.png)
That document image appears, and the map will not drag properly.
We don't see the issue when using the zoom controls.
We are using the most recent release of the jar file, and we are seeing the same issue on Mac and Windows.
Any help would be appreciated!
Thank you!

**Comment by lcoombe** [comment] 2016-07-12 20:28
Just to add to this - I also opened the jar file directly, and was seeing the same problem when I try to double-click to zoom.

**Comment by rterp** [comment] 2016-07-13 00:31
I'm seeing the same behavior as well.  Probably won't have time till the end of the week to debug, but it looks almost like the WebView component is getting focus, and the app is thinking that you want to drag-n-drop the component, rather than sending the drag event to the underlying map.

**Comment by lcoombe** [comment] 2016-07-13 06:36
Ah I see - Thanks so much for looking into this Rob!

**Comment by GeoffCapper** [comment] 2016-07-13 08:32
I'm not seeing this on mine using the 2.0.7 release so it might be platform dependent? I'm on win10 with JDK 1.8.0_92. Sorry I can't assist more due to that!

**Comment by rterp** [comment] 2016-07-15 20:40
So from what I've seen it appears that when you double click on the WebView, it then becomes the source of a Drag-n-Drop event, which when you click the next time to move the map, it actually is expecting the WebView itself to be dragged.  I've noticed however, that if you double click on the map with the right mouse button (to zoom out), and then attempt to move the map, by clicking and holding the right mouse button, the expected behavior happens.  

I believe this is a bug in JavaFX and not in the GMapsFX component itself.  The question is, is there a workaround for this?

**Comment by rterp** [comment] 2016-07-15 23:56
I've create a simple test case to demonstrate and issue and have submitted a bug report to bugreport.java.com.

I'll update this issue with the bug ID when its created, before closing this issue.

**Comment by lcoombe** [comment] 2016-07-16 06:53
Sounds good, thanks again Rob!

**Comment by lcoombe** [comment] 2016-07-18 16:00
Also, in the meantime, is there a functionality implemented to disable the double-click zoom?? Sorry if this is a bad question - I just couldn't find anything in the docs.
Thank you in advance!!

**Comment by rterp** [comment] 2016-07-18 23:03
I have added a method to the GoogleMapView object called setDisableDoubleClick().  Pass 'true' to this method, and the GoogleMapView component will consume the double click mouse event and not pass it to the underlying WebView, preventing the zoom on the underlying map.  I just did a release build of version 2.0.8 which contains this change.

hth,
-Rob

**Comment by lcoombe** [comment] 2016-07-18 23:44
That's perfect - thanks so much!

**Comment by rterp** [comment] 2016-07-20 16:53
Oracle has created issue JDK-8161892 to address this bug.
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8161892

will close this issue now.

**Closed by rterp** 2016-07-20 16:53 UTC
Labels: bug

**Comment by probsto** [comment] 2017-10-04 15:26
Thanks for your quick fix by introducing the "setDisableDoubleClick" method. Actually, the bug still exists if you click three times, four times etc. Would it be possible to replace the condition to > 1 (now it is == 2) ?
